In [1]:
import pandas as pd
import seaborn as sns
import numpy as np

In [2]:
data = pd.read_csv('AAAutoSprzedam_data.csv', sep=';')

In [3]:
data.created_date = pd.to_datetime(data.created_date)
data.deleted_date = pd.to_datetime(data.deleted_date)

In [4]:
stock_days2 = data.deleted_date - data.created_date

In [5]:
data['stock_days2'] = stock_days2

In [6]:
data.stock_days2 = data.stock_days2/np.timedelta64(1, 'D')
data.stock_days2 = data.stock_days2 + 1

In [7]:
data.stock_days2.min()

1.0

In [8]:
data[data.stock_days2 == 0]

Empty DataFrame
Columns: [article_id, product_tier, make_name, price, first_zip_digit, first_registration_year, created_date, deleted_date, search_views, detail_views, stock_days, ctr, stock_days2]
Index: []

In [9]:
data.drop('stock_days',axis=1,inplace=True)

In [10]:
data.article_id.value_counts().head(20)

359772384    2
360768628    2
360768627    2
364638423    2
350214315    2
360768625    2
360768632    2
360768624    2
354755824    2
350214314    2
354755822    2
360472733    2
357528924    2
360793587    2
358519054    2
354755829    2
359754168    1
349571668    1
360448597    1
350173618    1
Name: article_id, dtype: int64

In [11]:
data = data.drop_duplicates(subset='article_id', keep=False)

In [12]:
data.first_registration_year.replace(2106,2006,True)

In [13]:
data.first_registration_year.replace(2020,2002,True)

In [14]:
data['age'] = 2019 - data.first_registration_year

In [15]:
data = data.dropna()

In [16]:
data = data.drop('article_id', axis = 1)

In [17]:
cut_data = data[data['make_name'].isin(['Alfa Romeo', 'Audi', 'BMW', 'Caravans-Wohnm', 'Chevrolet',
       'Chrysler', 'Citroen', 'Dacia', 'Daewoo', 'Daihatsu', 'Dodge',
       'Fiat', 'Ford', 'Honda', 'Hyundai', 'Iveco', 'Jaguar', 'Jeep',
       'Kia', 'Lancia', 'Land Rover', 'Lexus', 'MINI', 'Mazda',
       'Mercedes-Benz', 'Mitsubishi', 'Nissan', 'Oldtimer', 'Opel',
       'Peugeot', 'Porsche', 'Renault', 'SEAT', 'Saab', 'Skoda', 'Subaru',
       'Suzuki', 'Tesla', 'Toyota', 'Volkswagen', 'Volvo', 'smart'])]

In [18]:
cut_data.to_csv(r'cut_data.csv')

In [19]:
pd.read_csv("cut_data.csv")

,Unnamed: 0,product_tier,make_name,price,first_zip_digit,first_registration_year,created_date,deleted_date,search_views,detail_views,ctr,stock_days2,age
0,0,Basic,Mitsubishi,16750,5,2013,2018-07-24,2018-08-24,3091.0,123.0,0.037803,32.0,6
1,1,Basic,Mercedes-Benz,35950,4,2015,2018-08-16,2018-10-07,3283.0,223.0,0.067926,53.0,4
2,2,Basic,Mercedes-Benz,11950,3,1998,2018-07-16,2018-09-05,3247.0,265.0,0.081614,52.0,21
3,3,Basic,Ford,1750,6,2003,2018-07-20,2018-10-29,1856.0,26.0,0.014009,102.0,16
4,4,Basic,Mercedes-Benz,26500,3,2014,2018-08-28,2018-09-08,490.0,20.0,0.040816,12.0,5
5,5,Basic,Volkswagen,24890,6,2017,2018-10-20,2018-10-22,125.0,6.0,0.048000,3.0,2
6,6,Basic,Fiat,2850,7,2008,2018-11-08,2018-11-09,172.0,4.0,0.022093,2.0,11
7,7,Basic,Renault,23740,2,2018,2018-11-20,2019-02-15,1499.0,99.0,0.062742,88.0,1
8,8,Basic,Renault,7850,6,2016,2018-09-24,2018-12-08,4329.0,133.0,0.030723,76.0,3
9,9,Basic,Mazda,13950,3,2016,2018-09-08,2018-10-10,2257.0,89.0,0.039433,33.0,3
10,10,Basic,Peugeot,12425,2,2017,2018-08-20,2018-11-19,639.0,6.0,0.008920,92.0,2
11,11,Basic,Fiat,6500,7,2010,2018-07-28,2018-08-28,1251.0,48.0,0.038369,32.0,9
12,12,Basic,Opel,6450,4,2007,2018-08-28,2018-09-10,1109.0,146.0,0.131650,14.0,12
13,13,Basic,Toyota,13945,7,2014,2018-07-24,2018-08-01,170.0,10.0,0.058824,9.0,5
14,14,Basic,Jaguar,69800,3,2018,2018-08-16,2018-09-03,630.0,11.0,0.017460,19.0,1
15,15,Basic,Ford,20400,6,2018,2018-10-20,2018-11-22,534.0,4.0,0.007491,34.0,1
16,16,Basic,Ford,14950,5,2014,2018-11-24,2019-01-31,3792.0,210.0,0.052611,69.0,5
17,17,Basic,Volvo,6450,7,2007,2018-09-28,2018-10-05,215.0,10.0,0.046512,8.0,12
18,18,Basic,Ford,10850,2,2013,2018-07-04,2018-07-17,428.0,10.0,0.023364,14.0,6
19,19,Basic,Renault,25900,7,2018,2018-11-20,2018-12-12,92.0,0.0,0.000000,23.0,1
20,20,Basic,Volvo,3750,7,2004,2018-11-20,2018-12-27,1139.0,41.0,0.035996,38.0,15
21,21,Basic,Peugeot,31400,3,2018,2018-11-16,2019-03-22,9432.0,344.0,0.036472,127.0,1
22,22,Basic,Dacia,13440,3,2014,2018-07-12,2018-09-15,2592.0,32.0,0.011728,66.0,5
23,23,Basic,Ford,7250,2,2007,2018-08-16,2018-11-02,1783.0,63.0,0.035334,79.0,12
24,24,Basic,MINI,21945,4,2013,2018-11-24,2018-12-17,1442.0,36.0,0.024965,24.0,6
25,25,Basic,Porsche,12950,5,2005,2018-08-04,2018-09-27,15318.0,1274.0,0.083170,55.0,14
26,26,Basic,Opel,11440,5,2012,2018-07-12,2018-08-26,1672.0,134.0,0.080144,46.0,7
27,27,Basic,Renault,18950,4,2018,2018-11-08,2018-11-21,83.0,1.0,0.012048,14.0,1
28,28,Basic,Nissan,21755,3,2015,2018-10-12,2018-12-01,1216.0,80.0,0.065789,51.0,4
29,29,Basic,BMW,8950,1,2009,2018-08-12,2018-12-09,2215.0,91.0,0.039029,120.0,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
77633,78291,Premium,Lexus,26799,7,2015,2018-09-12,2018-09-13,209.0,14.0,0.066986,2.0,4
77634,78292,Basic,Porsche,10950,2,1996,2018-09-20,2018-11-17,4406.0,182.0,0.041307,59.0,23
77635,78293,Basic,BMW,7950,4,2005,2018-11-24,2019-01-31,5254.0,251.0,0.047773,69.0,14
77636,78294,Basic,Citroen,5425,1,2012,2018-08-16,2018-08-31,330.0,27.0,0.081818,16.0,7
77637,78295,Premium,Mazda,1444,5,2005,2018-10-20,2018-10-27,10731.0,495.0,0.046128,8.0,14
77638,78296,Basic,Fiat,7840,5,2014,2018-08-08,2018-12-12,1106.0,8.0,0.007233,127.0,5
77639,78297,Basic,Opel,2399,3,2008,2018-08-04,2018-11-12,27609.0,2240.0,0.081133,101.0,11
77640,78298,Basic,Toyota,15250,8,2016,2018-07-04,2018-10-05,945.0,19.0,0.020106,94.0,3
77641,78299,Basic,Volkswagen,13900,8,2017,2018-10-12,2018-10-15,56.0,0.0,0.000000,4.0,2
77642,78300,Basic,Mercedes-Benz,24850,3,2015,2018-11-08,2018-11-19,594.0,56.0,0.094276,12.0,4
77643,78301,Basic,Peugeot,11800,1,2014,2018-09-20,2018-11-07,1262.0,79.0,0.062599,49.0,5
77644,78302,Basic,Kia,16950,4,2016,2018-09-04,2018-11-19,1467.0,54.0,0.036810,77.0,3
77645,78303,Basic,BMW,10850,6,2009,2018-09-04,2018-09-18,677.0,50.0,0.070162,15.0,10
77646,78304,Basic,Land Rover,7990,3,2007,2018-11-28,2018-11-30,500.0,29.0,0.055100,3.0,12
77647,78305,Basic,BMW,54750,3,2018,2018-07-12,2018-10-31,935.0,73.0,0.074171,112.0,1
77648,78306,Basic,BMW,7950,7,2009,2018-10-12,2018-11-06,7493.0,807.0,0.107701,26.0,10
77649,78307,Basic,Skoda,14950,3,2017,2018-10-04,2018-10-06,18.0,0.0,0.000000,3.0,2
77650,78308,Basic,Renault,1250,7,2000,2018-10-20,2018-12-22,3369.0,101.0,0.028480,64.0,19
77651,78309,Basic,Renault,15940,6,2014,2018-11-12,2018-11-21,334.0,27.0,0.080838,10.0,5
77652,78310,Basic,Iveco,27850,6,2016,2018-08-24,2018-10-30,723.0,16.0,0.022130,68.0,3
77653,78311,Basic,Opel,1299,3,2004,2018-07-20,2018-08-14,950.0,24.0,0.025263,26.0,15
77654,78312,Basic,Daihatsu,2749,3,2008,2018-08-08,2018-08-14,388.0,16.0,0.041237,7.0,11
77655,78313,Basic,Renault,6950,5,2011,2018-08-08,2018-10-08,4316.0,284.0,0.065802,62.0,8
77656,78314,Basic,BMW,3999,8,2005,2018-11-08,2018-12-28,7149.0,189.0,0.025115,51.0,14
77657,78315,Basic,Ford,3297,3,2008,2018-09-20,2018-09-24,604.0,34.0,0.056291,5.0,11
77658,78316,Basic,Lexus,15740,8,2014,2018-07-12,2018-10-19,6895.0,230.0,0.033358,100.0,5
77659,78317,Basic,Hyundai,2950,6,2006,2018-09-28,2018-10-23,1175.0,16.0,0.012936,26.0,13
77660,78318,Basic,Volkswagen,7850,8,2014,2018-11-04,2018-11-21,448.0,21.0,0.046875,18.0,5
77661,78319,Basic,Toyota,13945,5,2011,2018-09-04,2018-10-02,1617.0,29.0,0.017934,29.0,8
77662,78320,Basic,Volkswagen,38800,7,2018,2018-08-08,2018-08-09,55.0,2.0,0.034545,2.0,1

In [22]:
cut_data.groupby("make_name").count()

,product_tier,price,first_zip_digit,first_registration_year,created_date,deleted_date,search_views,detail_views,ctr,stock_days2,age
make_name,,,,,,,,,,,
Alfa Romeo,532,532,532,532,532,532,532,532,532,532,532
Audi,3311,3311,3311,3311,3311,3311,3311,3311,3311,3311,3311
BMW,4551,4551,4551,4551,4551,4551,4551,4551,4551,4551,4551
Caravans-Wohnm,95,95,95,95,95,95,95,95,95,95,95
Chevrolet,485,485,485,485,485,485,485,485,485,485,485
Chrysler,117,117,117,117,117,117,117,117,117,117,117
Citroen,3017,3017,3017,3017,3017,3017,3017,3017,3017,3017,3017
Dacia,440,440,440,440,440,440,440,440,440,440,440
Daewoo,91,91,91,91,91,91,91,91,91,91,91
Daihatsu,197,197,197,197,197,197,197,197,197,197,197
Dodge,139,139,139,139,139,139,139,139,139,139,139
Fiat,2588,2588,2588,2588,2588,2588,2588,2588,2588,2588,2588
Ford,5196,5196,5196,5196,5196,5196,5196,5196,5196,5196,5196
Honda,536,536,536,536,536,536,536,536,536,536,536
Hyundai,1800,1800,1800,1800,1800,1800,1800,1800,1800,1800,1800
Iveco,222,222,222,222,222,222,222,222,222,222,222
Jaguar,275,275,275,275,275,275,275,275,275,275,275
Jeep,160,160,160,160,160,160,160,160,160,160,160
Kia,1931,1931,1931,1931,1931,1931,1931,1931,1931,1931,1931
Lancia,77,77,77,77,77,77,77,77,77,77,77
Land Rover,545,545,545,545,545,545,545,545,545,545,545
Lexus,303,303,303,303,303,303,303,303,303,303,303
MINI,1234,1234,1234,1234,1234,1234,1234,1234,1234,1234,1234
Mazda,1198,1198,1198,1198,1198,1198,1198,1198,1198,1198,1198
Mercedes-Benz,4756,4756,4756,4756,4756,4756,4756,4756,4756,4756,4756
Mitsubishi,1067,1067,1067,1067,1067,1067,1067,1067,1067,1067,1067
Nissan,2014,2014,2014,2014,2014,2014,2014,2014,2014,2014,2014
Oldtimer,108,108,108,108,108,108,108,108,108,108,108
Opel,5215,5215,5215,5215,5215,5215,5215,5215,5215,5215,5215
Peugeot,5446,5446,5446,5446,5446,5446,5446,5446,5446,5446,5446
Porsche,524,524,524,524,524,524,524,524,524,524,524
Renault,6948,6948,6948,6948,6948,6948,6948,6948,6948,6948,6948
SEAT,1769,1769,1769,1769,1769,1769,1769,1769,1769,1769,1769
Saab,186,186,186,186,186,186,186,186,186,186,186
Skoda,1514,1514,1514,1514,1514,1514,1514,1514,1514,1514,1514
Subaru,162,162,162,162,162,162,162,162,162,162,162
Suzuki,1312,1312,1312,1312,1312,1312,1312,1312,1312,1312,1312
Tesla,84,84,84,84,84,84,84,84,84,84,84
Toyota,3922,3922,3922,3922,3922,3922,3922,3922,3922,3922,3922
Volkswagen,9424,9424,9424,9424,9424,9424,9424,9424,9424,9424,9424
Volvo,3989,3989,3989,3989,3989,3989,3989,3989,3989,3989,3989
smart,183,183,183,183,183,183,183,183,183,183,183